In [5]:
import pandas as pd

df = pd.read_csv('pokemon_data.csv')

#print(df.tail(5))

# Import excel file
# df_xl = pd.read_excel('pokemon_data.xlsx')

# Import txt file
# df = pd.read_csv('pokemon_data.txt', delimiter='\t')

In [6]:
# Read headers
#df.columns

#Read each column
#print(df[['Name', 'Type 1', 'HP']])

#Read each row
#print(df.iloc[4:7])
#for index, row in df.iterrows():
#print(index, row['Legendary'])

# Read based on specific attribute
df.loc[df['Type 1'] == 'Fire']
    
#Read a specific location (R,C)
#print(df.iloc[4,1])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [7]:
# Basic statistical metrics of the datafram
#df.describe()

# Sort values per attributes, in ascending or descending order
df.sort_values(['Attack', 'HP'], ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True

In [8]:
# Adding columns and making changes to the data

# df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
# df.head(5)

# Dropping a selected column
df.drop(columns=['Total'])

# Adding a column in reference to locations
df['Total'] = df.iloc[:, 4:10].sum(axis=1)

# Rearrangin the columns
cols = list(df.columns)
df = df[cols[0:4] + [cols[-1]] + cols [4:12]]
df.head(5)

KeyError: "['Total'] not found in axis"

In [ ]:
# Saving the dataframe in different data files, without the index columm

df.to_csv('modified.csv', index=False)

df.to_excel('modified.xlsx', index=False)

df.to_csv('modified.txt', index=False, sep='\t')

In [ ]:
# Filtering data

new_df = df.loc[(df['Type 1'] == 'Fire') & (df['Type 2'] == 'Flying') & (df['HP'] > 70)]
# The original indexes remain, so reset_index
new_df.reset_index(drop=True, inplace=True)
new_df
new_df.to_csv('fire_flying.csv')

In [ ]:
# Filtering using a string in a value

df.loc[df['Name'].str.contains('Mega')]
# df.loc[~df['Name'].str.contains('Mega')] ~ to indicate not

In [ ]:
# Filter for result containing a regular expression
import re

# df.loc[df['Type 1'].str.contains('fire|grass', case=False, regex=True)]
df.loc[df['Name'].str.contains('^pi[a-z]*', case=False, regex=True)]

In [17]:
# Conditional changes. Change Type 1 Fire to Flamer

# df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'

# Change all Grass to Legendary
# df.loc[df['Type 1'] == 'Grass', 'Legendary']=True

# Change multiple values at the same time
# df.loc[df['Total']>500, ['Type 1', 'Legendary']] = ['Strong', 'True']

# Reloading checkpoint df because it is screwed up now
df = pd.read_csv('modified.csv')

In [27]:
# Groupby aggregate statistics
# Mean values based on Type 1
# df.groupby(['Type 1']).mean().sort_values('Attack', ascending=False)
# Total value based on Type 1
# df.groupby(['Type 1']).sum()
# Amount of values based on Type 1
df['Count'] = 1
df.groupby(['Type 1', 'HP']).count()['Count']

Type 1  HP
Bug     1      1
        20     1
        30     2
        31     1
        35     1
              ..
Water   111    1
        125    1
        130    3
        165    1
        170    1
Name: Count, Length: 389, dtype: int64

In [34]:
# Working with large data, loading chunks of a file
new_df = pd.DataFrame(columns=df.columns)

for df in pd.read_csv('modified.csv', chunksize=5):
    results = df.groupby(['Type 1']).count()
    
    new_df = pd.concat([new_df, results], sort=True)
    
new_df

,#,Attack,Defense,Generation,HP,Legendary,Name,Sp. Atk,Sp. Def,Speed,Total,Type 1,Type 2
Fire,1,1,1,1,1,1,1,1,1,1,1,NaN,0
Grass,4,4,4,4,4,4,4,4,4,4,4,NaN,4
Fire,4,4,4,4,4,4,4,4,4,4,4,NaN,3
Water,1,1,1,1,1,1,1,1,1,1,1,NaN,0
Bug,2,2,2,2,2,2,2,2,2,2,2,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Fairy,1,1,1,1,1,1,1,1,1,1,1,NaN,0
Flying,2,2,2,2,2,2,2,2,2,2,2,NaN,2
Fire,1,1,1,1,1,1,1,1,1,1,1,NaN,1
Psychic,2,2,2,2,2,2,2,2,2,2,2,NaN,2
Rock,2,2,2,2,2,2,2,2,2,2,2,NaN,2